version: "3"

services:
  www:
    build: .
    restart: always
    volumes:
      - ./html:/var/www/html/
    ports:
      - 9001:80
    depends_on:
      - mysql
  mysql:
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_DATABASE: recette_manager
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    ports:
      - "3360:3306"
    volumes:
      - db-dfs:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-dfs: